ALTER TABLE credit_notes
    ADD COLUMN IF NOT EXISTS notes TEXT NULL AFTER status;

ALTER TABLE client_returns
    ADD COLUMN IF NOT EXISTS total_amount DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER status;

ALTER TABLE client_returns
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE client_return_items
    ADD COLUMN IF NOT EXISTS unit_price DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER condition_status;
